Repository kakao-tech-campus-2nd-step3/Team21_BE, pull requests merged in 2024-11, with the labels that each got.

#76 feat: 파일 수정 API에서 파일을 첨부하지 않아도 되도록 수정
  src/main/java/com/potatocake/everymoment/controller/CommentController.java
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/controller/FileController.java
  src/main/java/com/potatocake/everymoment/dto/request/CategoryCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FcmTokenRequest.java
  src/main/java/com/potatocake/everymoment/entity/Comment.java
  src/main/java/com/potatocake/everymoment/entity/DeviceToken.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/File.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/service/FileService.java
Labels: ✨ feat

#77 merge: 9주차 작업 master에 반영
  src/main/java/com/potatocake/everymoment/controller/CommentController.java
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/controller/FileController.java
  src/main/java/com/potatocake/everymoment/dto/request/CategoryCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FcmTokenRequest.java
  src/main/java/com/potatocake/everymoment/entity/Comment.java
  src/main/java/com/potatocake/everymoment/entity/DeviceToken.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/File.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/FileService.java
Labels: 📦 merge

#80 feat: 일기 필터링/수정, 친구 일기 조회 기능 수정
  src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendDiarySpecification.java
Labels: 🐛 bug, ✨ feat

#82 bug: 친구 일기 조회 안되는 오류 수정
  src/main/java/com/potatocake/everymoment/service/FriendDiarySpecification.java
Labels: 🐛 bug

#84 feat: 익명 로그인 API 구현
  src/main/java/com/potatocake/everymoment/config/SecurityConfig.java
  src/main/java/com/potatocake/everymoment/config/SwaggerConfig.java
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/dto/response/AnonymousLoginResponse.java
  src/main/java/com/potatocake/everymoment/repository/MemberRepository.java
  src/main/java/com/potatocake/everymoment/service/MemberService.java
Labels: ✨ feat

#86 feat: 친구 일기 수정
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendService.java
Labels: ✨ feat

#90 feat: 일기에 대한 좋아요 상태 응답 필드 추가
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/dto/request/CategoryRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryAutoCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java
  src/main/java/com/potatocake/everymoment/repository/LikeRepository.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/LikeService.java
  src/main/resources/application-prod.yml
  src/test/java/com/potatocake/everymoment/controller/DiaryControllerTest.java
  src/test/java/com/potatocake/everymoment/entity/DiaryTest.java
  src/test/java/com/potatocake/everymoment/repository/DiaryRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/DiaryServiceTest.java
Labels: ✨ feat

#93 test: 누락된 테스트 코드 작성
  .github/workflows/master_weekly_cicd.yml
  .github/workflows/pr_weekly_ci.yml
  src/main/java/com/potatocake/everymoment/dto/request/CategoryCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FcmTokenRequest.java
  src/main/java/com/potatocake/everymoment/entity/Like.java
  src/test/java/com/potatocake/everymoment/controller/CategoryControllerTest.java
  src/test/java/com/potatocake/everymoment/controller/CommentControllerTest.java
  src/test/java/com/potatocake/everymoment/controller/FcmControllerTest.java
  src/test/java/com/potatocake/everymoment/controller/FileControllerTest.java
  src/test/java/com/potatocake/everymoment/controller/FriendControllerTest.java
  src/test/java/com/potatocake/everymoment/controller/FriendRequestControllerTest.java
  src/test/java/com/potatocake/everymoment/controller/LikeControllerTest.java
  src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java
  src/test/java/com/potatocake/everymoment/entity/CategoryTest.java
  src/test/java/com/potatocake/everymoment/entity/CommentTest.java
  src/test/java/com/potatocake/everymoment/entity/DeviceTokenTest.java
  src/test/java/com/potatocake/everymoment/entity/FileTest.java
  src/test/java/com/potatocake/everymoment/entity/FriendRequestTest.java
  src/test/java/com/potatocake/everymoment/entity/FriendTest.java
  src/test/java/com/potatocake/everymoment/entity/LikeTest.java
  src/test/java/com/potatocake/everymoment/entity/MemberTest.java
  src/test/java/com/potatocake/everymoment/repository/CategoryRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/CommentRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/DeviceTokenRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/DiaryRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/FileRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/FriendRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/FriendRequestRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/LikeRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/MemberRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/CategoryServiceTest.java
  src/test/java/com/potatocake/everymoment/service/CommentServiceTest.java
  src/test/java/com/potatocake/everymoment/service/FcmServiceTest.java
  src/test/java/com/potatocake/everymoment/service/FileServiceTest.java
  src/test/java/com/potatocake/everymoment/service/FriendRequestServiceTest.java
  src/test/java/com/potatocake/everymoment/service/FriendServiceTest.java
  src/test/java/com/potatocake/everymoment/service/LikeServiceTest.java
  src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java
Labels: 🔨 test

#94 feat: 댓글 개수 반환 API 추가
  src/main/java/com/potatocake/everymoment/controller/CommentController.java
  src/main/java/com/potatocake/everymoment/dto/response/CommentResponse.java
  src/main/java/com/potatocake/everymoment/repository/CommentRepository.java
  src/main/java/com/potatocake/everymoment/service/CommentService.java
Labels: ✨ feat

#96 fix: JWT 인증 문제 해결 및 추가 테스트 코드 작성
  .github/workflows/master_weekly_cicd.yml
  .github/workflows/pr_weekly_ci.yml
  src/main/java/com/potatocake/everymoment/util/JwtUtil.java
  src/main/resources/application-prod.yml
  src/test/java/com/potatocake/everymoment/controller/NotificationControllerTest.java
  src/test/java/com/potatocake/everymoment/entity/NotificationTest.java
  src/test/java/com/potatocake/everymoment/repository/NotificationRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/NotificationServiceTest.java
  src/test/java/com/potatocake/everymoment/util/IdExtractorTest.java
  src/test/java/com/potatocake/everymoment/util/JwtUtilTest.java
  src/test/java/com/potatocake/everymoment/util/PagingUtilTest.java
  src/test/java/com/potatocake/everymoment/util/S3FileUploaderTest.java
Labels: 🐛 bug, 🔨 test

#100 feat: 비관적 락 제거 및 로그 추가
  src/main/java/com/potatocake/everymoment/repository/MemberRepository.java
  src/main/resources/application-prod.yml
Labels: ✨ feat

#101 feat: 프로필 이미지 업데이트 로직에 로그 추가
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
Labels: ✨ feat

#103 feat: 불필요한 로그 제거
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/resources/application-prod.yml
Labels: ✨ feat

#105 feat: 수기일기 수정, 알람 조회순 변경
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiarySimpleResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/repository/NotificationRepository.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/NotificationService.java
  src/test/java/com/potatocake/everymoment/repository/NotificationRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/NotificationServiceTest.java
Labels: 🐛 bug, ✨ feat

#107 fix: 좋아요 데이터 동시성 제어
  src/main/java/com/potatocake/everymoment/entity/Like.java
  src/main/java/com/potatocake/everymoment/repository/LikeRepository.java
  src/main/java/com/potatocake/everymoment/service/LikeService.java
Labels: 🐛 bug

#108 fix: 비관적 락 적용으로 테스트 코드 수정
  src/test/java/com/potatocake/everymoment/repository/LikeRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/LikeServiceTest.java
Labels: 🐛 bug

#110 feat: 검색 조건에 공유 여부 추가
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/test/java/com/potatocake/everymoment/repository/DiaryRepositoryTest.java
Labels: ✨ feat

#112 feat: 테스트 커버리지 측정 자동화
  .github/workflows/pr_weekly_ci.yml
  build.gradle
Labels: ✨ feat

#114 merge: 11주차 작업 master에 반영
  .github/workflows/pr_weekly_ci.yml
  README.md
  build.gradle
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiarySimpleResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/Like.java
  src/main/java/com/potatocake/everymoment/repository/LikeRepository.java
  src/main/java/com/potatocake/everymoment/repository/MemberRepository.java
  src/main/java/com/potatocake/everymoment/repository/NotificationRepository.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/LikeService.java
  src/main/java/com/potatocake/everymoment/service/NotificationService.java
  src/test/java/com/potatocake/everymoment/repository/DiaryRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/LikeRepositoryTest.java
  src/test/java/com/potatocake/everymoment/repository/NotificationRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/LikeServiceTest.java
  src/test/java/com/potatocake/everymoment/service/NotificationServiceTest.java
Labels: 📦 merge
