Repository kakao-tech-campus-2nd-step3/Team21_BE, pull requests merged in 2024-09, with the labels that each got.

#5 init: 프로젝트 초기 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/potatocake/everymoment/EverymomentApplication.java
  src/main/java/com/potatocake/everymoment/config/.gitkeep
  src/main/java/com/potatocake/everymoment/controller/.gitkeep
  src/main/java/com/potatocake/everymoment/dto/SuccessResponse.java
  src/main/java/com/potatocake/everymoment/dto/request/.gitkeep
  src/main/java/com/potatocake/everymoment/dto/response/.gitkeep
  src/main/java/com/potatocake/everymoment/entity/BaseTimeEntity.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/exception/ErrorResponse.java
  src/main/java/com/potatocake/everymoment/exception/GlobalException.java
  src/main/java/com/potatocake/everymoment/exception/GlobalExceptionHandler.java
  src/main/java/com/potatocake/everymoment/exception/ValidationErrorMessage.java
  src/main/java/com/potatocake/everymoment/repository/.gitkeep
  src/main/java/com/potatocake/everymoment/security/.gitkeep
  src/main/java/com/potatocake/everymoment/service/.gitkeep
  src/main/java/com/potatocake/everymoment/util/.gitkeep
  src/main/resources/application.yml
  src/test/java/com/potatocake/everymoment/EverymomentApplicationTests.java
Labels: 🛠️ setup

#8 feat: 내 일기 API 기능 구현
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/dto/LocationPoint.java
  src/main/java/com/potatocake/everymoment/dto/request/CategoryRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryAutoRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FileRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/CategoryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FileResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiariesResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiarySimpleResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/NotificationResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/ThumbnailResponse.java
  src/main/java/com/potatocake/everymoment/entity/BaseTimeEntity.java
  src/main/java/com/potatocake/everymoment/entity/Category.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/DiaryCategory.java
  src/main/java/com/potatocake/everymoment/entity/Notification.java
  src/main/java/com/potatocake/everymoment/repository/DiaryCategoryRepository.java
  src/main/java/com/potatocake/everymoment/repository/DiaryRepository.java
  src/main/java/com/potatocake/everymoment/repository/NotificationRepository.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
Labels: ✨ feat

#9 feat: 회원가입 및 로그인 구현
  build.gradle
  src/main/java/com/potatocake/everymoment/config/.gitkeep
  src/main/java/com/potatocake/everymoment/config/JpaAuditingConfig.java
  src/main/java/com/potatocake/everymoment/config/SecurityConfig.java
  src/main/java/com/potatocake/everymoment/constant/Constants.java
  src/main/java/com/potatocake/everymoment/dto/SuccessResponse.java
  src/main/java/com/potatocake/everymoment/dto/request/.gitkeep
  src/main/java/com/potatocake/everymoment/dto/request/MemberLoginRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/.gitkeep
  src/main/java/com/potatocake/everymoment/dto/response/JwtResponse.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/exception/GlobalExceptionHandler.java
  src/main/java/com/potatocake/everymoment/exception/ValidationErrorMessage.java
  src/main/java/com/potatocake/everymoment/repository/.gitkeep
  src/main/java/com/potatocake/everymoment/repository/MemberRepository.java
  src/main/java/com/potatocake/everymoment/security/.gitkeep
  src/main/java/com/potatocake/everymoment/security/MemberAuthenticationService.java
  src/main/java/com/potatocake/everymoment/security/MemberDetails.java
  src/main/java/com/potatocake/everymoment/security/filter/JwtFilter.java
  src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
  src/main/java/com/potatocake/everymoment/security/handler/Http401Handler.java
  src/main/java/com/potatocake/everymoment/util/.gitkeep
  src/main/java/com/potatocake/everymoment/util/JwtUtil.java
Labels: ✨ feat

#11 feat: Github Actions로 CI/CD 자동 배포 구축
  .github/workflows/deploy.yml
  src/main/java/com/potatocake/everymoment/dto/SuccessResponse.java
Labels: 🚀 deploy

#12 merge: 3주차 작업 master에 반영
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/potatocake/everymoment/EverymomentApplication.java
  src/main/java/com/potatocake/everymoment/config/JpaAuditingConfig.java
  src/main/java/com/potatocake/everymoment/config/SecurityConfig.java
  src/main/java/com/potatocake/everymoment/constant/Constants.java
  src/main/java/com/potatocake/everymoment/controller/.gitkeep
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/dto/LocationPoint.java
  src/main/java/com/potatocake/everymoment/dto/SuccessResponse.java
  src/main/java/com/potatocake/everymoment/dto/request/CategoryRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryAutoRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FileRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/MemberLoginRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/CategoryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FileResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/JwtResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiariesResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiarySimpleResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/NotificationResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/ThumbnailResponse.java
  src/main/java/com/potatocake/everymoment/entity/BaseTimeEntity.java
  src/main/java/com/potatocake/everymoment/entity/Category.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/DiaryCategory.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/entity/Notification.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/exception/ErrorResponse.java
  src/main/java/com/potatocake/everymoment/exception/GlobalException.java
  src/main/java/com/potatocake/everymoment/exception/GlobalExceptionHandler.java
  src/main/java/com/potatocake/everymoment/exception/ValidationErrorMessage.java
  src/main/java/com/potatocake/everymoment/repository/DiaryCategoryRepository.java
  src/main/java/com/potatocake/everymoment/repository/DiaryRepository.java
  src/main/java/com/potatocake/everymoment/repository/MemberRepository.java
  src/main/java/com/potatocake/everymoment/repository/NotificationRepository.java
  src/main/java/com/potatocake/everymoment/security/MemberAuthenticationService.java
  src/main/java/com/potatocake/everymoment/security/MemberDetails.java
  src/main/java/com/potatocake/everymoment/security/filter/JwtFilter.java
  src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
  src/main/java/com/potatocake/everymoment/security/handler/Http401Handler.java
  src/main/java/com/potatocake/everymoment/service/.gitkeep
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/util/JwtUtil.java
  src/main/resources/application.yml
  src/test/java/com/potatocake/everymoment/EverymomentApplicationTests.java
Labels: 📦 merge

#15 merge: CI/CD 에러 해결 master에 반영
  .github/workflows/deploy.yml
Labels: 🐛 bug, 📦 merge

#20 feat: 회원 관련 API 구현 및 CI 관련 워크플로우 추가
  .github/workflows/master_cicd.yml
  .github/workflows/pr_weekly_ci.yml
  .gitignore
  build.gradle
  src/main/java/com/potatocake/everymoment/config/AwsS3Properties.java
  src/main/java/com/potatocake/everymoment/config/SecurityConfig.java
  src/main/java/com/potatocake/everymoment/controller/.gitkeep
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/dto/SuccessResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberDetailResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResponse.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/exception/GlobalExceptionHandler.java
  src/main/java/com/potatocake/everymoment/repository/MemberRepository.java
  src/main/java/com/potatocake/everymoment/security/MemberDetails.java
  src/main/java/com/potatocake/everymoment/security/filter/JwtFilter.java
  src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
  src/main/java/com/potatocake/everymoment/service/.gitkeep
  src/main/java/com/potatocake/everymoment/service/MemberService.java
  src/main/java/com/potatocake/everymoment/util/PagingUtil.java
  src/main/java/com/potatocake/everymoment/util/S3FileUploader.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java
  src/test/java/com/potatocake/everymoment/repository/MemberRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java
  src/test/java/com/potatocake/everymoment/util/PagingUtilTest.java
Labels: ✨ feat, 🚀 deploy

#24 feat: 중복된 enum 제거 및 weekly 브랜치 병합 시 CI/CD 트리거 추가
  .github/workflows/master_weekly_cicd.yml
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
Labels: 🐛 bug, 🚀 deploy

#29 feat: Swagger 설정 및 로그인 HttpMethod 설정
  .github/workflows/master_weekly_cicd.yml
  src/main/java/com/potatocake/everymoment/config/SwaggerConfig.java
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
Labels: ✨ feat
