Repository kakao-tech-campus-2nd-step3/Team21_BE, pull requests merged in 2024-10, with the labels that each got.

#30 feat: 파일 조회/저장/수정 API 구현
  src/main/java/com/potatocake/everymoment/controller/FileController.java
  src/main/java/com/potatocake/everymoment/dto/request/FileRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/FileResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/File.java
  src/main/java/com/potatocake/everymoment/repository/FileRepository.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/FileService.java
Labels: ✨ feat

#33 feat: 카테고리 API 구현
  src/main/java/com/potatocake/everymoment/controller/CategoryController.java
  src/main/java/com/potatocake/everymoment/dto/request/CategoryCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/CategoryResponse.java
  src/main/java/com/potatocake/everymoment/entity/Category.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/exception/ErrorResponse.java
  src/main/java/com/potatocake/everymoment/repository/CategoryRepository.java
  src/main/java/com/potatocake/everymoment/service/CategoryService.java
Labels: ✨ feat

#35 feat: 친구 추가/좋아요 API 구현
  src/main/java/com/potatocake/everymoment/controller/FriendRequestController.java
  src/main/java/com/potatocake/everymoment/controller/LikeController.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendRequestPageRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendRequestResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/LikeCountResponse.java
  src/main/java/com/potatocake/everymoment/entity/FriendRequest.java
  src/main/java/com/potatocake/everymoment/entity/Like.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/repository/FriendRepository.java
  src/main/java/com/potatocake/everymoment/repository/FriendRequestRepository.java
  src/main/java/com/potatocake/everymoment/repository/LikeRepository.java
  src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
  src/main/java/com/potatocake/everymoment/service/LikeService.java
  src/main/java/com/potatocake/everymoment/service/MemberService.java
  src/main/java/com/potatocake/everymoment/util/IdExtractor.java
  src/main/java/com/potatocake/everymoment/util/PagingUtil.java
  src/test/java/com/potatocake/everymoment/util/PagingUtilTest.java
Labels: ✨ feat

#37 feat: 요구 사항 반영 및 회원 탈퇴 API 구현
  src/main/java/com/potatocake/everymoment/controller/FriendController.java
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/dto/request/MemberLoginRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberDetailResponse.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/exception/ValidationErrorMessage.java
  src/main/java/com/potatocake/everymoment/repository/MemberRepository.java
  src/main/java/com/potatocake/everymoment/security/MemberAuthenticationService.java
  src/main/java/com/potatocake/everymoment/security/MemberDetails.java
  src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
  src/main/java/com/potatocake/everymoment/service/FriendService.java
  src/main/java/com/potatocake/everymoment/service/FriendSpecification.java
  src/main/java/com/potatocake/everymoment/service/MemberService.java
  src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java
  src/test/java/com/potatocake/everymoment/repository/MemberRepositoryTest.java
  src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java
Labels: ✨ feat

#42 fix: 내 일기 및 친구 일기 조회 에러 해결
  src/main/java/com/potatocake/everymoment/dto/response/CommentsResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendDiariesResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendListResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiariesResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/OneFriendDiariesResponse.java
  src/main/java/com/potatocake/everymoment/entity/Friend.java
  src/main/java/com/potatocake/everymoment/repository/FriendRepository.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
  src/main/java/com/potatocake/everymoment/service/FriendService.java
  src/main/java/com/potatocake/everymoment/service/FriendSpecification.java
Labels: 🐛 bug

#44 fix: 회원 정보 수정 API 에러 해결
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/service/MemberService.java
Labels: 🐛 bug

#46 feat: 사용자 검색 시 친구 요청 상태 추가
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendRequestStatus.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberMyResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResultResponse.java
  src/main/java/com/potatocake/everymoment/repository/FriendRepository.java
  src/main/java/com/potatocake/everymoment/repository/FriendRequestRepository.java
  src/main/java/com/potatocake/everymoment/service/MemberService.java
  src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java
  src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java
Labels: ✨ feat

#49 feat: Swagger API 문서에 설명 추가 및 타임존 설정
  .github/workflows/master_weekly_cicd.yml
  src/main/java/com/potatocake/everymoment/controller/CategoryController.java
  src/main/java/com/potatocake/everymoment/controller/CommentController.java
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/controller/FileController.java
  src/main/java/com/potatocake/everymoment/controller/FriendController.java
  src/main/java/com/potatocake/everymoment/controller/FriendRequestController.java
  src/main/java/com/potatocake/everymoment/controller/LikeController.java
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/controller/NotificationController.java
  src/main/resources/application-prod.yml
Labels: ✨ feat

#51 deploy: RDS (MySQL) 생성 및 연동
  .github/workflows/master_weekly_cicd.yml
  .github/workflows/pr_weekly_ci.yml
  src/main/resources/application-prod.yml
Labels: 🚀 deploy

#52 feat: 일기 API 추가 구현
  build.gradle
  src/main/java/com/potatocake/everymoment/config/GeometryConfig.java
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/dto/LocationPoint.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/exception/ErrorResponse.java
  src/main/java/com/potatocake/everymoment/repository/DiaryCategoryRepository.java
  src/main/java/com/potatocake/everymoment/repository/FileRepository.java
  src/main/java/com/potatocake/everymoment/security/MemberDetails.java
  src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
  src/main/java/com/potatocake/everymoment/service/CommentService.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendService.java
Labels: ✨ feat

#54 merge: 6주차 작업 master에 반영
  .github/workflows/master_weekly_cicd.yml
  .github/workflows/pr_weekly_ci.yml
  build.gradle
  src/main/java/com/potatocake/everymoment/config/GeometryConfig.java
  src/main/java/com/potatocake/everymoment/controller/CategoryController.java
  src/main/java/com/potatocake/everymoment/controller/CommentController.java
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/controller/FileController.java
  src/main/java/com/potatocake/everymoment/controller/FriendController.java
  src/main/java/com/potatocake/everymoment/controller/FriendRequestController.java
  src/main/java/com/potatocake/everymoment/controller/LikeController.java
  src/main/java/com/potatocake/everymoment/controller/MemberController.java
  src/main/java/com/potatocake/everymoment/controller/NotificationController.java
  src/main/java/com/potatocake/everymoment/dto/LocationPoint.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/CommentsResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendDiariesResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendListResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendRequestStatus.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberMyResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResultResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiariesResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java
  src/main/java/com/potatocake/everymoment/dto/response/OneFriendDiariesResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/Friend.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/exception/ErrorResponse.java
  src/main/java/com/potatocake/everymoment/repository/DiaryCategoryRepository.java
  src/main/java/com/potatocake/everymoment/repository/FileRepository.java
  src/main/java/com/potatocake/everymoment/repository/FriendRepository.java
  src/main/java/com/potatocake/everymoment/repository/FriendRequestRepository.java
  src/main/java/com/potatocake/everymoment/security/MemberDetails.java
  src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
  src/main/java/com/potatocake/everymoment/service/CommentService.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
  src/main/java/com/potatocake/everymoment/service/FriendService.java
  src/main/java/com/potatocake/everymoment/service/FriendSpecification.java
  src/main/java/com/potatocake/everymoment/service/MemberService.java
  src/main/resources/application-prod.yml
  src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java
  src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java
Labels: 📦 merge

#56 feat: 친구 요청 목록 API에서 사용자 정보도 응답 필드에 추가
  src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendRequestResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/DiaryCategory.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
Labels: ✨ feat

#58 feat: 파일 업로드 관련 API 수정
  src/main/java/com/potatocake/everymoment/controller/FileController.java
  src/main/java/com/potatocake/everymoment/dto/request/FileRequest.java
  src/main/java/com/potatocake/everymoment/service/FileService.java
Labels: ✨ feat

#62 fix: 친구 일기 조회 API 에러 수정
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
Labels: 🐛 bug

#64 feat: FCM 푸쉬 알림 구현
  .github/workflows/master_weekly_cicd.yml
  .github/workflows/pr_weekly_ci.yml
  .gitignore
  build.gradle
  src/main/java/com/potatocake/everymoment/config/FcmConfig.java
  src/main/java/com/potatocake/everymoment/controller/FcmController.java
  src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FcmNotificationRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FcmTokenRequest.java
  src/main/java/com/potatocake/everymoment/entity/DeviceToken.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/repository/DeviceTokenRepository.java
  src/main/java/com/potatocake/everymoment/service/CommentService.java
  src/main/java/com/potatocake/everymoment/service/FcmService.java
  src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
  src/main/java/com/potatocake/everymoment/service/LikeService.java
  src/test/java/com/potatocake/everymoment/EverymomentApplicationTests.java
  src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java
Labels: ✨ feat

#66 feat: 알림 table에 저장될 데이터 및 FCM 알림 통일
  src/main/java/com/potatocake/everymoment/constant/NotificationType.java
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/service/CommentService.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/FcmService.java
  src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
  src/main/java/com/potatocake/everymoment/service/LikeService.java
  src/main/java/com/potatocake/everymoment/service/NotificationService.java
Labels: ✨ feat

#67 merge: 8주차 작업 master에 반영
  .github/workflows/master_weekly_cicd.yml
  .github/workflows/pr_weekly_ci.yml
  .gitignore
  build.gradle
  src/main/java/com/potatocake/everymoment/config/FcmConfig.java
  src/main/java/com/potatocake/everymoment/constant/NotificationType.java
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/controller/FcmController.java
  src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FcmNotificationRequest.java
  src/main/java/com/potatocake/everymoment/dto/request/FcmTokenRequest.java
  src/main/java/com/potatocake/everymoment/entity/DeviceToken.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
  src/main/java/com/potatocake/everymoment/repository/DeviceTokenRepository.java
  src/main/java/com/potatocake/everymoment/service/CommentService.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/FcmService.java
  src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
  src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
  src/main/java/com/potatocake/everymoment/service/LikeService.java
  src/main/java/com/potatocake/everymoment/service/NotificationService.java
  src/test/java/com/potatocake/everymoment/EverymomentApplicationTests.java
  src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java
Labels: 📦 merge

#69 feat: 다이어리 기능/오류 수정 및 친한친구 기능 삭제
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/controller/FriendController.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendProfileResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/Friend.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/FriendService.java
  src/main/resources/application-prod.yml
Labels: ✨ feat

#71 fix: CI/CD 배포 오류 수정
  .github/workflows/pr_weekly_ci.yml
  src/test/java/com/potatocake/everymoment/repository/MemberRepositoryTest.java
Labels: 🐛 bug

#72 merge: CI/CD 배포 오류 해결 반영
  .github/workflows/pr_weekly_ci.yml
  src/main/java/com/potatocake/everymoment/controller/DiaryController.java
  src/main/java/com/potatocake/everymoment/controller/FriendController.java
  src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java
  src/main/java/com/potatocake/everymoment/dto/response/FriendProfileResponse.java
  src/main/java/com/potatocake/everymoment/entity/Diary.java
  src/main/java/com/potatocake/everymoment/entity/Friend.java
  src/main/java/com/potatocake/everymoment/entity/Member.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
  src/main/java/com/potatocake/everymoment/service/FriendService.java
  src/main/resources/application-prod.yml
  src/test/java/com/potatocake/everymoment/repository/MemberRepositoryTest.java
Labels: 📦 merge

#74 fix: 일기 필터링 오류 수정
  src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java
  src/main/java/com/potatocake/everymoment/service/DiaryService.java
  src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
Labels: 🐛 bug
